---

- name: Install Yum Repo
  template:
    src=influxdb.repo.j2
    dest=/etc/yum.repos.d/influxdb.repo
    owner=root
    group=root
    mode=0644

- name: Import GPG Key
  rpm_key:
    key=https://repos.influxdata.com/influxdb.key
    state=present

- name: Install InfluxDB
  package:
    name=influxdb
    state=latest

- name: Start InfluxDB
  service:
    name=influxdb
    state=started
